version: 0.2

env:
  variables:
    AWS_REGION: "ap-south-1"
    ECR_REPOSITORY: "share-co2"
    ECS_CLUSTER: "share-co2"
    ECS_SERVICE: "share-co2-service"
    CONTAINER_NAME: "share-co2"

phases:
  pre_build:
    commands:
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - echo "AWS Account ID: $AWS_ACCOUNT_ID"
      - "echo \"Logging in to Amazon ECR...\""
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - ECR_REGISTRY=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - FULL_IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
  build:
    commands:
      - docker build -t $ECR_REPOSITORY:latest .
      - docker tag $ECR_REPOSITORY:latest $FULL_IMAGE_URI
  post_build:
    commands:
      - docker push $FULL_IMAGE_URI
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $FULL_IMAGE_URI > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
